### ISSUE TITLE
XMinioStorageFull

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/topobank-stack-development#15]
When uploading measurments, development stack raises

botocore.exceptions.ClientError: An error occurred (XMinioStorageFull) when calling the CreateMultipartUpload operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.10/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/formtools/wizard/views.py", line 244, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/formtools/wizard/views.py", line 302, in post
    return self.render_done(form, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/formtools/wizard/views.py", line 358, in render_done
    done_response = self.done(list(final_forms.values()), form_dict=final_forms, **kwargs)
  File "/app-topobank/topobank/manager/views.py", line 442, in done
    instance.datafile = default_storage.save(new_path, File(f))
  File "/usr/local/lib/python3.10/site-packages/django/core/files/storage.py", line 54, in save
    name = self._save(name, content)
  File "/usr/local/lib/python3.10/site-packages/storages/backends/s3boto3.py", line 445, in _save
    obj.upload_fileobj(content, ExtraArgs=params, Config=self._transfer_config)
  File "/usr/local/lib/python3.10/site-packages/boto3/s3/inject.py", line 725, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "/usr/local/lib/python3.10/site-packages/boto3/s3/inject.py", line 636, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.10/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/s3transfer/tasks.py", line 348, in _main
    response = client.create_multipart_upload(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (XMinioStorageFull) when calling the CreateMultipartUpload operation: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.
```

Versions are

```
Module | Version | License | Links
-- | -- | -- | --
TopoBank | 1.0.0 | MIT | Website , Changelog
SurfaceTopography | 1.3.3 | MIT | Website , Changelog
ContactMechanics | 1.1.1 | MIT | Website , Changelog
NuMPI | 0.3.1 | MIT | Website , Changelog
muFFT | 0.25.2 | LGPL-3 | Website , Changelog
NumPy | 1.23.5 | BSD 3-Clause | Website
SciPy | 1.10.0 | BSD 3-Clause | Website
Django | 3.2.16 | BSD 3-Clause | Website
Celery | 5.2.7 | BSD 3-Clause | Website
Bokeh | 3.0.0dev4 | BSD 3-Clause | Website
OpenSeadragon | 2.4.2 | BSD 3-Clause | Website
```

**Comment by jotelha** [comment]
This is really just due to disk space runnin out on wherever the docker stuff grows.
