### ISSUE TITLE
docker compose up fails

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/topobank-stack-development#16]
with

```
topobank-stack-development-2023-04-03-django-1                | Traceback (most recent call last):
topobank-stack-development-2023-04-03-django-1                |   File "/development-stack/topobank/topobank/__init__.py", line 3, in <module>
topobank-stack-development-2023-04-03-django-1                |     __version__ = version("topobank")
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
topobank-stack-development-2023-04-03-django-1                |     return distribution(distribution_name).version
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
topobank-stack-development-2023-04-03-django-1                |     return Distribution.from_name(distribution_name)
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
topobank-stack-development-2023-04-03-django-1                |     raise PackageNotFoundError(name)
topobank-stack-development-2023-04-03-django-1                | importlib.metadata.PackageNotFoundError: No package metadata was found for topobank
topobank-stack-development-2023-04-03-django-1                | 
topobank-stack-development-2023-04-03-django-1                | During handling of the above exception, another exception occurred:
topobank-stack-development-2023-04-03-django-1                | 
topobank-stack-development-2023-04-03-django-1                | Traceback (most recent call last):
topobank-stack-development-2023-04-03-django-1                |   File "/development-stack/topobank/manage.py", line 30, in <module>
topobank-stack-development-2023-04-03-django-1                |     execute_from_command_line(sys.argv)
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
topobank-stack-development-2023-04-03-django-1                |     utility.execute()
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
topobank-stack-development-2023-04-03-django-1                |     settings.INSTALLED_APPS
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
topobank-stack-development-2023-04-03-django-1                |     self._setup(name)
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
topobank-stack-development-2023-04-03-django-1                |     self._wrapped = Settings(settings_module)
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
topobank-stack-development-2023-04-03-django-1                |     mod = importlib.import_module(self.SETTINGS_MODULE)
topobank-stack-development-2023-04-03-django-1                |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
topobank-stack-development-2023-04-03-django-1                |     return _bootstrap._gcd_import(name[level:], package, level)
topobank-stack-development-2023-04-03-django-1                |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
topobank-stack-development-2023-04-03-django-1                |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
topobank-stack-development-2023-04-03-django-1                |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
topobank-stack-development-2023-04-03-django-1                |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
topobank-stack-development-2023-04-03-django-1                |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
topobank-stack-development-2023-04-03-django-1                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
topobank-stack-development-2023-04-03-django-1                |   File "/development-stack/topobank/config/settings/local.py", line 1, in <module>
topobank-stack-development-2023-04-03-django-1                |     from .base import *  # noqa
topobank-stack-development-2023-04-03-django-1                |   File "/development-stack/topobank/config/settings/base.py", line 16, in <module>
topobank-stack-development-2023-04-03-django-1                |     import topobank
topobank-stack-development-2023-04-03-django-1                |   File "/development-stack/topobank/topobank/__init__.py", line 4, in <module>
topobank-stack-development-2023-04-03-django-1                |     except PackageNotFoundError:
topobank-stack-development-2023-04-03-django-1                | NameError: name 'PackageNotFoundError' is not defined. Did you mean: 'ModuleNotFoundError'?
```

This looks like Python not knowing its exception `PackageNotFoundError` in the lines https://github.com/ContactEngineering/topobank/blob/5f79b84a9d43bb34cf45035c32247edd27f5aa54/topobank/__init__.py#L3-L4 of topobank.

**Comment by jotelha** [comment]
Issue is fixed in https://github.com/ContactEngineering/topobank/compare/prepare_v1.0.2
